///
/// @Generated by Mockolo
///



import Foundation
import Vapor
@testable import Domain


public final class IMembershipRepositoryMock: IMembershipRepository, @unchecked Sendable {
    public init() { }


    private let createState = MockoloMutex(MockoloHandlerState<Never, @Sendable (Membership) async throws -> ()>())
    public var createCallCount: Int {
        return createState.withLock(\.callCount)
    }
    public var createHandler: (@Sendable (Membership) async throws -> ())? {
        get { createState.withLock(\.handler) }
        set { createState.withLock { $0.handler = newValue } }
    }
    public func create(_ membership: Membership) async throws {
        let createHandler = createState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let createHandler = createHandler {
            try await createHandler(membership)
        }
        
    }

    private let updateState = MockoloMutex(MockoloHandlerState<Never, @Sendable (Membership) async throws -> ()>())
    public var updateCallCount: Int {
        return updateState.withLock(\.callCount)
    }
    public var updateHandler: (@Sendable (Membership) async throws -> ())? {
        get { updateState.withLock(\.handler) }
        set { updateState.withLock { $0.handler = newValue } }
    }
    public func update(_ membership: Membership) async throws {
        let updateHandler = updateState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let updateHandler = updateHandler {
            try await updateHandler(membership)
        }
        
    }

    private let deleteState = MockoloMutex(MockoloHandlerState<Never, @Sendable (UUID) async throws -> ()>())
    public var deleteCallCount: Int {
        return deleteState.withLock(\.callCount)
    }
    public var deleteHandler: (@Sendable (UUID) async throws -> ())? {
        get { deleteState.withLock(\.handler) }
        set { deleteState.withLock { $0.handler = newValue } }
    }
    public func delete(id: UUID) async throws {
        let deleteHandler = deleteState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let deleteHandler = deleteHandler {
            try await deleteHandler(id)
        }
        
    }

    private let findState = MockoloMutex(MockoloHandlerState<Never, @Sendable (UUID) async throws -> Membership?>())
    public var findCallCount: Int {
        return findState.withLock(\.callCount)
    }
    public var findHandler: (@Sendable (UUID) async throws -> Membership?)? {
        get { findState.withLock(\.handler) }
        set { findState.withLock { $0.handler = newValue } }
    }
    public func find(id: UUID) async throws -> Membership? {
        let findHandler = findState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let findHandler = findHandler {
            return try await findHandler(id)
        }
        return nil
    }

    private let findUserIdState = MockoloMutex(MockoloHandlerState<Never, @Sendable (UUID) async throws -> [Membership]>())
    public var findUserIdCallCount: Int {
        return findUserIdState.withLock(\.callCount)
    }
    public var findUserIdHandler: (@Sendable (UUID) async throws -> [Membership])? {
        get { findUserIdState.withLock(\.handler) }
        set { findUserIdState.withLock { $0.handler = newValue } }
    }
    public func find(userId: UUID) async throws -> [Membership] {
        let findUserIdHandler = findUserIdState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let findUserIdHandler = findUserIdHandler {
            return try await findUserIdHandler(userId)
        }
        return [Membership]()
    }

    private let findMembershipTypeIdState = MockoloMutex(MockoloHandlerState<Never, @Sendable (UUID) async throws -> [Membership]>())
    public var findMembershipTypeIdCallCount: Int {
        return findMembershipTypeIdState.withLock(\.callCount)
    }
    public var findMembershipTypeIdHandler: (@Sendable (UUID) async throws -> [Membership])? {
        get { findMembershipTypeIdState.withLock(\.handler) }
        set { findMembershipTypeIdState.withLock { $0.handler = newValue } }
    }
    public func find(membershipTypeId: UUID) async throws -> [Membership] {
        let findMembershipTypeIdHandler = findMembershipTypeIdState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let findMembershipTypeIdHandler = findMembershipTypeIdHandler {
            return try await findMembershipTypeIdHandler(membershipTypeId)
        }
        return [Membership]()
    }

    private let findAllState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async throws -> [Membership]>())
    public var findAllCallCount: Int {
        return findAllState.withLock(\.callCount)
    }
    public var findAllHandler: (@Sendable () async throws -> [Membership])? {
        get { findAllState.withLock(\.handler) }
        set { findAllState.withLock { $0.handler = newValue } }
    }
    public func findAll() async throws -> [Membership] {
        let findAllHandler = findAllState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let findAllHandler = findAllHandler {
            return try await findAllHandler()
        }
        return [Membership]()
    }
}

fileprivate func warnIfNotSendable<each T>(function: String = #function, _: repeat each T) {
    print("At \(function), the captured arguments are not Sendable, it is not concurrency-safe.")
}

fileprivate func warnIfNotSendable<each T: Sendable>(function: String = #function, _: repeat each T) {
}

/// Will be replaced to `Synchronization.Mutex` in future.
fileprivate final class MockoloMutex<Value>: @unchecked Sendable {
    private let lock = NSLock()
    private var value: Value
    init(_ initialValue: Value) {
        self.value = initialValue
    }
#if compiler(>=6.0)
    borrowing func withLock<Result, E: Error>(_ body: (inout sending Value) throws(E) -> Result) throws(E) -> sending Result {
        lock.lock()
        defer { lock.unlock() }
        return try body(&value)
    }
#else
    func withLock<Result>(_ body: (inout Value) throws -> Result) rethrows -> Result {
        lock.lock()
        defer { lock.unlock() }
        return try body(&value)
    }
#endif
}

fileprivate struct MockoloUnsafeTransfer<Value>: @unchecked Sendable {
    var value: Value
    init(_ value: Value) {
        self.value = value
    }
}

fileprivate struct MockoloHandlerState<Arg, Handler> {
    var argValues: [MockoloUnsafeTransfer<Arg>] = []
    var handler: Handler? = nil
    var callCount: Int = 0
}

