name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04

    env:
      CONFIG_PATH: ./src/Shared/config.json

    services:
      postgres-test:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5433:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Swift
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6.0"

      - name: Show Swift version
        run: swift --version

      - name: Set permissions for Bash-scripts
        run: chmod +x src/TestScripts/*.sh

      - name: Set permissions for Py-scripts
        run: chmod +x src/TestScripts/*.py

      - name: Initialize database
        working-directory: src
        run: sh -x TestScripts/create_db.sh
        
      - name: Create results folder
        run: mkdir -p TestResults

      - name: Check if results folder exists
        run: |
          if [ ! -d "TestResults" ]; then"
            exit 1
          fi
