name: Testing

on:
  workflow_dispatch:

jobs:
  start-db:
    runs-on: ubuntu-22.04
    outputs:
      db-ip: ${{ steps.get-ip.outputs.ip }}

    services:
      postgres-test:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5433:5432

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Get Ubuntu runner IP
        id: get-ip
        run: |
          echo "ip=$(hostname -I | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Wait for DB to be ready
        run: |
          until docker exec fitapp_db_test pg_isready -U postgres -d testdb; do
            echo "Waiting for DB..."
            sleep 2
          done

  test-on-macos:
    runs-on: macos-latest
    needs: start-db
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install PostgreSQL client
        run: brew install libpq

      - name: Test DB connection
        run: |
          export PATH="/opt/homebrew/opt/libpq/bin:$PATH"
          PGPASSWORD=password psql -h ${{ needs.start-db.outputs.db-ip }} -p 5433 -U postgres -d testdb -c "SELECT version();"
