name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest

    env:
      CONFIG_PATH: ./src/Shared/config.json

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Docker on macOS
        uses: douglascamata/setup-docker-macos-action@v1.0.0
        with:
          colima: latest
          colima-network-address: true

      - name: Check Docker
        run: docker version

      # 🐘 Поднимаем Postgres контейнер
      - name: Run Postgres
        run: |
          docker run -d \
            --name postgres-test \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=password \
            -e POSTGRES_DB=testdb \
            -p 5433:5432 \
            postgres:16-alpine
          sleep 5

      - name: Check Swift
        run: swift --version

      - name: Set permissions for scripts
        run: chmod +x src/TestScripts/*.sh

      - name: Initialize database
        run: ./create_db.sh
