name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-version:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Swift
        uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
        with:
          swift-version: "5.3"

      - name: Show Swift version
        run: swift --version
