name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-job:
    runs-on: macos-15-intel
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Docker on macOS
        uses: douglascamata/setup-docker-macos-action@v1.0.0
        with:
          colima-additional-options: "--cpu 4 --memory 4"

      - name: Check Docker version
        run: docker --version

      - name: Run Docker container
        run: |
          docker run --rm alpine echo "Hello from Docker"
