name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest

    env:
      CONFIG_PATH: ./src/Shared/config.json

    services:
      postgres-test:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5433:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Swift
        run: brew install swift

      - name: Install Allure
        run: brew install allure

      - name: Set permissions for scripts
        run: chmod +x src/TestScripts/*.sh

      - name: Initialize database
        run: ./create_db.sh

      - name: Run tests
        working-directory: src
        run: ./TestScripts/run_tests.sh true

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: src/TestResults/AllureReport

