name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CONFIG_PATH: ./src/Shared/config.json

    services:
      postgres-test:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5433:5432
        options: >-
          --mount type=bind,source=${{ github.workspace }}/src/Shared/db/init-scripts,target=/docker-entrypoint-initdb.d
          --restart=unless-stopped

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Start Docker Compose services
        run: |
          docker-compose -f ./src/docker-compose.yml up -d
          docker-compose -f ./src/docker-compose.yml ps

      - name: Install Swift
        run: sudo apt-get update && sudo apt-get install -y swift

      - name: Install Allure
        run: |
          sudo apt-add-repository ppa:qameta/allure
          sudo apt-get update
          sudo apt-get install -y allure

      - name: Set permissions for scripts
        run: chmod +x src/TestScripts/*.sh

      - name: Run tests
        working-directory: src
        run: ./TestScripts/run_tests.sh true

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: src/TestResults/AllureReport

      - name: Tear down Docker Compose services
        run: docker-compose -f ./src/docker-compose.yml down

