name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-version:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Swift
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6.0"

      - name: Show Swift version
        run: swift --version
