name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-version:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.9.0"

      - name: Show Swift version
        run: swift --version
